DEFINE DBFILE_EXT = '.DBF'
DEFINE DATA_TBS = '_DATA'
DEFINE IDX_TBS = '_IDX'

CREATE TABLESPACE &1&DATA_TBS DATAFILE '&2\&1&DATA_TBS&DBFILE_EXT' SIZE 1G AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED;
CREATE TABLESPACE &1&IDX_TBS DATAFILE '&2\&1&IDX_TBS&DBFILE_EXT' SIZE 1G AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED;
