PROMPT ====CREATE_PRIVELEGES====

DEFINE DATA_TBS = '_DATA'
DEFINE IDX_TBS = '_IDX'

ALTER USER &1 QUOTA UNLIMITED ON &1&DATA_TBS;
ALTER USER &1 QUOTA UNLIMITED ON &1&IDX_TBS;

GRANT CONNECT TO &1;
GRANT CREATE ANY TABLE TO &1;
GRANT CREATE ANY PROCEDURE TO &1;