PROMPT ==== DROP_TABLESPACES====

DEFINE DATA_TBS = '_DATA'
DEFINE IDX_TBS = '_IDX'

DROP TABLESPACE &1&DATA_TBS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE &1&IDX_TBS INCLUDING CONTENTS AND DATAFILES;
